[tool.poetry]
name = "cine-scrapper"
version = "0.1.0"
description = ""
authors = ["Lennon <lennon.ribeiro@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
beautifulsoup4 = "4.13.4"
certifi = "2025.8.3"
charset-normalizer = "3.4.2"
dotenv = "0.9.9"
html5lib = "1.1"
idna = "3.10"
python-dotenv = "1.1.1"
requests = "2.32.4"
six = "1.17.0"
soupsieve = "2.7"
typing-extensions = "4.14.1"
urllib3 = "2.5.0"
webencodings = "0.5.1"
redis = "^6.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
